export { suppliersRoutes } from "./routes.tsx";
export { default as Suppliers } from "./pages/Suppliers";
export { default as SuppliersList } from "./pages/SuppliersList";
export { default as MaterialsList } from "./pages/MaterialsList";
export { default as ExplosionsList } from "./pages/ExplosionsList";
export { default as ExplosionDetail } from "./pages/ExplosionDetail";
export { default as ProductionOrdersList } from "./pages/ProductionOrdersList";
export { default as ProductionOrderDetail } from "./pages/ProductionOrderDetail";
export { default as ProcessesList } from "./pages/ProcessesList";
export { AddSupplierModal } from "./components/suppliers/AddSupplierModal";
export { AddMaterialModal } from "./components/materials/AddMaterialModal";
export { AddServiceModal } from "./components/services/AddServiceModal";
