-- Ensure auto-increment IDs for orders table and related tables
ALTER TABLE public.orders
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.order_products
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.order_payment
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
