-- Create return_payments table for tracking payment movements in returns
CREATE TABLE public.return_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id BIGINT NOT NULL REFERENCES public.returns(id) ON DELETE CASCADE,
  movement_id BIGINT NOT NULL REFERENCES public.movements(id),
  payment_method_id BIGINT NOT NULL REFERENCES public.payment_methods(id),
  amount NUMERIC NOT NULL,
  payment_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  voucher_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  created_by UUID NOT NULL DEFAULT auth.uid() REFERENCES public.profiles("UID")
);

-- Enable RLS
ALTER TABLE public.return_payments ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Authenticated users can view return_payments"
ON public.return_payments FOR SELECT
USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can create return_payments"
ON public.return_payments FOR INSERT
WITH CHECK (auth.uid() = created_by);

-- Add class for returns in movements classes
INSERT INTO public.classes (module_id, code, name)
VALUES (
  (SELECT id FROM modules WHERE code = 'MOV'),
  'RTU',
  'Devoluciones/Cambios'
) ON CONFLICT DO NOTHING;