// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://wwcdntjnpoaacarmmzir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Y2RudGpucG9hYWNhcm1temlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzQzNTAsImV4cCI6MjA2MDQxMDM1MH0.Jk4_duO04oxRLGs35aWpXiDBOcxFsb9D7wvbYSV-yi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

//
